name: Tests
on: [push, pull_request]
jobs:
  Run-Tests:
    runs-on: ubuntu-22.04
    env: 
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd ${{ github.workspace }}
      - name: Run checker
        run: |
          cd tests/
          python3 ../run-tests.py         
          echo $?