name: Tests
on: [push, pull_request]
jobs:
  Run-Tests:
    runs-on: ubuntu-22.04
    env: 
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd ${{ github.workspace }}
      - name: Run checker (passing)
        run: |
          cd tests/pass/
          python3 ../../run-tests.py         
      - name: Run checker (failing)
        run: |
          cd tests/fail/
          ! python3 ../../run-tests.py    